<x-app-layout>
    <x-slot name="header"><div><span class="badge-ms">المعاملات</span><h2 class="mt-2">إضافة عملية مالية</h2></div></x-slot>
    <div class="py-8"><div class="max-w-5xl mx-auto px-4"><form method="POST" action="{{ route('acp.entry.store') }}" id="entry-form">@csrf
        <div class="bg-white rounded-lg p-6 shadow-sm mb-5"><div class="grid grid-cols-1 md:grid-cols-2 gap-5"><div><label for="date">تاريخ العملية</label><input id="date" type="date" name="date" value="{{ old('date', $today) }}" required></div><div><label for="note">وصف العملية</label><input id="note" name="note" value="{{ old('note') }}" placeholder="مثال: مصروفات البيت الأسبوعية"></div></div></div>
        <div class="bg-white rounded-lg p-6 shadow-sm"><div class="flex items-center justify-between mb-5"><div><h3 class="text-lg font-bold">تفاصيل العملية</h3><p class="text-sm text-gray-500">أضف سطرًا لكل حساب أو تصنيف داخل العملية.</p></div><button type="button" class="btn-ms" id="add-record">+ إضافة سطر</button></div><x-auth-validation-errors class="alert" :errors="$errors" /><div id="records"></div><div class="mt-6 grid grid-cols-1 md:grid-cols-3 gap-3"><div class="rounded-lg p-4" style="background:#e9f5ee"><small>إجمالي الإيرادات</small><strong id="total-income" class="block text-xl text-green-700">0.00</strong></div><div class="rounded-lg p-4" style="background:#fff0e4"><small>إجمالي المصروفات</small><strong id="total-expense" class="block text-xl text-red-600">0.00</strong></div><div class="rounded-lg p-4" style="background:#f2f7f3"><small>الفرق</small><strong id="total-difference" class="block text-xl">0.00</strong></div></div><div class="flex justify-end gap-3 mt-6"><a class="btn-light px-5 py-2" href="{{ route('acp.entry.index') }}">إلغاء</a><button class="btn-ms" type="submit">حفظ العملية كاملة</button></div></div>
    </form></div></div>
    <template id="record-template"><div class="record-row rounded-lg p-4 mb-4" style="background:#f8fbf8;border:1px solid #e3ebe5"><div class="grid grid-cols-1 md:grid-cols-6 gap-3 items-end"><div><label>النوع</label><select class="record-type" name="records[__INDEX__][type]"><option value="-1">مصروف</option><option value="1">إيراد</option></select></div><div><label>الحساب</label><select name="records[__INDEX__][account_id]" required><option value="">اختر الحساب</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></div><div><label>التصنيف</label><select name="records[__INDEX__][category_id]"><option value="">بدون تصنيف</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div><label>المبلغ</label><input class="record-value" type="number" name="records[__INDEX__][value]" min="0.01" step="0.01" required placeholder="0.00"></div><div><label>الوصف</label><input type="text" name="records[__INDEX__][comment]" maxlength="255" placeholder="ملاحظة اختيارية"></div><button type="button" class="remove-record text-red-600 px-2 py-2">حذف</button></div></div></template>
    <script>
        (()=>{const box=document.getElementById('records'),tpl=document.getElementById('record-template').innerHTML,add=document.getElementById('add-record');let i=0;const update=()=>{let income=0,expense=0;box.querySelectorAll('.record-row').forEach(row=>{const value=parseFloat(row.querySelector('.record-value').value)||0;if(row.querySelector('.record-type').value==='1')income+=value;else expense+=value});document.getElementById('total-income').textContent=income.toFixed(2);document.getElementById('total-expense').textContent=expense.toFixed(2);document.getElementById('total-difference').textContent=(income-expense).toFixed(2)};const addRow=()=>{box.insertAdjacentHTML('beforeend',tpl.replaceAll('__INDEX__',i++));const row=box.lastElementChild;row.querySelector('.remove-record').addEventListener('click',()=>{row.remove();update()});row.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',update));update()};add.addEventListener('click',addRow);addRow()})();
    </script>
</x-app-layout>
