<x-app-layout>
    <x-slot name="header"><div><span class="badge-ms">المعاملات</span><h2 class="mt-2">إضافة عملية مالية</h2></div></x-slot>
    <div class="py-8"><div class="max-w-5xl mx-auto px-4"><form method="POST" action="{{ route('acp.entry.store') }}" id="entry-form">@csrf<input type="hidden" name="entry_type" value="expense">
        <div class="bg-white rounded-lg p-6 shadow-sm mb-5"><div class="grid grid-cols-1 md:grid-cols-3 gap-5"><div><label for="date">تاريخ العملية</label><input id="date" type="date" name="date" value="{{ old('date', $today) }}" required></div><div><label for="note">وصف العملية</label><input id="note" name="note" value="{{ old('note') }}" placeholder="مثال: مشتريات السوبر ماركت"></div><div><label for="total_amount">القيمة الإجمالية</label><input id="total_amount" type="number" name="total_amount" value="{{ old('total_amount') }}" min="0.01" step="0.01" required placeholder="1000.00"></div></div><p class="text-sm text-gray-500 mt-4">احفظ العملية أولًا، ثم أضف تفاصيل السطور وحدد الحساب الذي تم الدفع منه.</p></div>
        <div class="bg-white rounded-lg p-6 shadow-sm"><h3 class="text-lg font-bold mb-3">التفاصيل لاحقًا</h3><p class="text-gray-600">بعد الحفظ ستدخل على تعديل العملية لإضافة الطماطم والبطاطس وتحديد الحساب المدفوع منه.</p><div class="flex justify-end gap-3 mt-6"><a class="btn-light px-5 py-2" href="{{ route('acp.entry.index') }}">إلغاء</a><button class="btn-ms" type="submit">حفظ العملية</button></div></div>
    <div class="bg-white rounded-lg p-6 shadow-sm mb-5"><label for="entry_type">نوع العملية</label><select id="entry_type" name="entry_type" required><option value="expense">مصروف</option><option value="income">دخل / راتب</option><option value="transfer">تحويل داخلي</option><option value="refund">استرداد</option><option value="other">أخرى</option></select></div></form></div></div>
    <template id="record-template"><div class="record-row rounded-lg p-4 mb-4" style="background:#f8fbf8;border:1px solid #e3ebe5"><div class="grid grid-cols-1 md:grid-cols-6 gap-3 items-end"><div><label>النوع</label><select class="record-type" name="records[__INDEX__][type]"><option value="-1">مصروف</option><option value="1">إيراد</option></select></div><div><label>الحساب</label><select name="records[__INDEX__][account_id]" required><option value="">اختر الحساب</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></div><div><label>التصنيف</label><select name="records[__INDEX__][category_id]"><option value="">بدون تصنيف</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div><label>المبلغ</label><input class="record-value" type="number" name="records[__INDEX__][value]" min="0.01" step="0.01" required placeholder="0.00"></div><div><label>الوصف</label><input type="text" name="records[__INDEX__][comment]" maxlength="255" placeholder="ملاحظة اختيارية"></div><button type="button" class="remove-record text-red-600 px-2 py-2">حذف</button></div></div></template>
    <script>
        (()=>{const box=document.getElementById('records'),tpl=document.getElementById('record-template').innerHTML,add=document.getElementById('add-record');let i=0;const update=()=>{let income=0,expense=0;box.querySelectorAll('.record-row').forEach(row=>{const value=parseFloat(row.querySelector('.record-value').value)||0;if(row.querySelector('.record-type').value==='1')income+=value;else expense+=value});document.getElementById('total-income').textContent=income.toFixed(2);document.getElementById('total-expense').textContent=expense.toFixed(2);document.getElementById('total-difference').textContent=(income-expense).toFixed(2)};const addRow=()=>{box.insertAdjacentHTML('beforeend',tpl.replaceAll('__INDEX__',i++));const row=box.lastElementChild;row.querySelector('.remove-record').addEventListener('click',()=>{row.remove();update()});row.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',update));update()};add.addEventListener('click',addRow);addRow()})();
    </script>
</x-app-layout>
