<x-app-layout>
    <x-slot name="header"><h2>تعديل العملية {{ $entry->reference_number }}</h2></x-slot>
    <div class="py-8"><div class="max-w-6xl mx-auto px-4"><form method="POST" action="{{ route('acp.entry.update', $entry) }}" enctype="multipart/form-data">@csrf @method('PUT')
        <div class="bg-white rounded-lg p-6 shadow-sm mb-5 grid gap-4 md:grid-cols-4"><div><label>التاريخ</label><input type="date" name="date" value="{{ old('date', $entry->date?->format('Y-m-d')) }}" required></div><div><label>نوع العملية</label><select name="entry_type"><option value="expense" @selected($entry->entry_type === 'expense')>مصروف</option><option value="income" @selected($entry->entry_type === 'income')>دخل / راتب</option><option value="transfer" @selected($entry->entry_type === 'transfer')>تحويل داخلي</option><option value="refund" @selected($entry->entry_type === 'refund')>استرداد</option><option value="other" @selected($entry->entry_type === 'other')>أخرى</option></select></div><div><label>الوصف</label><input name="note" value="{{ old('note', $entry->note) }}"></div><div><label>الإجمالي</label><input type="number" name="total_amount" value="{{ old('total_amount', $entry->total_amount) }}" min="0.01" step="0.01" required></div></div>
        <x-auth-validation-errors class="alert" :errors="$errors" />
        <div class="grid grid-cols-1 xl:grid-cols-2 gap-5"><section class="bg-white rounded-lg p-6 shadow-sm"><div class="flex justify-between items-center mb-4"><div><h3 class="text-lg font-bold">مصادر الدفع</h3><p class="text-sm text-gray-500">من أي حساب تم دفع أو استلام المبلغ؟</p></div><button type="button" class="btn-ms" id="add-payment">+ مصدر</button></div><div id="payments">@foreach($entry->paymentSplits as $i => $split)<div class="payment-row grid grid-cols-1 md:grid-cols-3 gap-2 mb-3"><select name="payment_splits[{{ $i }}][account_id]" required>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($split->account_id == $account->id)>{{ $account->name }}</option>@endforeach</select><input type="number" name="payment_splits[{{ $i }}][amount]" value="{{ $split->amount }}" min="0.01" step="0.01" required><button type="button" class="remove-payment text-red-600">حذف</button></div>@endforeach</div></section>
        <section class="bg-white rounded-lg p-6 shadow-sm"><div class="flex justify-between items-center mb-4"><div><h3 class="text-lg font-bold">بنود العملية</h3><p class="text-sm text-gray-500">كيف توزّع إجمالي العملية؟</p></div><button type="button" class="btn-ms" id="add-record">+ بند</button></div><div id="records">@foreach($entry->records as $i => $record)<div class="record-row grid grid-cols-1 md:grid-cols-5 gap-2 mb-3"><select name="records[{{ $i }}][category_id]"><option value="">بدون تصنيف</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($record->category_id == $category->id)>{{ $category->name }}</option>@endforeach</select><select name="records[{{ $i }}][account_id]" required>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($record->account_id == $account->id)>{{ $account->name }}</option>@endforeach</select><select name="records[{{ $i }}][type]"><option value="-1" @selected($record->type < 0)>مصروف</option><option value="1" @selected($record->type > 0)>دخل</option></select><input type="number" name="records[{{ $i }}][value]" value="{{ $record->value }}" min="0.01" step="0.01" required><button type="button" class="remove-record text-red-600">حذف</button></div>@endforeach</div></section></div>
        <div class="flex justify-end gap-3 mt-5"><a class="btn-light px-5 py-2" href="{{ route('acp.entry.show', $entry) }}">إلغاء</a><button class="btn-ms" type="submit">حفظ العملية</button></div>
        <div class="bg-white rounded-lg p-6 shadow-sm mt-5"><label for="attachments">إرفاق فواتير أو إيصالات</label><input id="attachments" type="file" name="attachments[]" multiple accept=".jpg,.jpeg,.png,.webp,.pdf"><p class="text-sm text-gray-500 mt-2">حتى 10 ملفات، وبحد أقصى 10MB للملف.</p></div>
    </form></div></div>
    <template id="payment-template"><div class="payment-row grid grid-cols-1 md:grid-cols-3 gap-2 mb-3"><select name="payment_splits[__INDEX__][account_id]" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select><input type="number" name="payment_splits[__INDEX__][amount]" min="0.01" step="0.01" required><button type="button" class="remove-payment text-red-600">حذف</button></div></template>
    <template id="record-template"><div class="record-row grid grid-cols-1 md:grid-cols-5 gap-2 mb-3"><select name="records[__INDEX__][category_id]"><option value="">بدون تصنيف</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select><select name="records[__INDEX__][account_id]" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select><select name="records[__INDEX__][type]"><option value="-1">مصروف</option><option value="1">دخل</option></select><input type="number" name="records[__INDEX__][value]" min="0.01" step="0.01" required><button type="button" class="remove-record text-red-600">حذف</button></div></template>
    <script>(()=>{let p={{ $entry->paymentSplits->count() }},r={{ $entry->records->count() }};const bind=(root,cls)=>root.querySelector(cls).addEventListener('click',()=>root.remove());const add=(button,box,tpl,cls,count)=>button.addEventListener('click',()=>{box.insertAdjacentHTML('beforeend',tpl.replaceAll('__INDEX__',count.value++));bind(box.lastElementChild,cls)});const pb=document.getElementById('payments'),rb=document.getElementById('records');pb.querySelectorAll('.payment-row').forEach(x=>bind(x,'.remove-payment'));rb.querySelectorAll('.record-row').forEach(x=>bind(x,'.remove-record'));add(document.getElementById('add-payment'),pb,document.getElementById('payment-template').innerHTML,'.remove-payment',{value:p});add(document.getElementById('add-record'),rb,document.getElementById('record-template').innerHTML,'.remove-record',{value:r})})();</script>
</x-app-layout>
