<x-app-layout>
    <x-slot name="header"><h2>تعديل العملية</h2></x-slot>
    <div class="py-8"><div class="max-w-5xl mx-auto px-4"><form method="POST" action="{{ route('acp.entry.update', $entry) }}">@csrf @method('PUT')
        <div class="bg-white rounded-lg p-6 shadow-sm mb-5 grid gap-5"><div><label for="date">تاريخ العملية</label><input id="date" type="date" name="date" value="{{ old('date', $entry->date?->format('Y-m-d')) }}" required></div><div><label for="note">وصف العملية</label><input id="note" name="note" value="{{ old('note', $entry->note) }}"></div></div>
        <div class="bg-white rounded-lg p-6 shadow-sm"><div class="flex items-center justify-between mb-5"><h3 class="text-lg font-bold">تفاصيل العملية</h3><button type="button" class="btn-ms" id="add-record">+ إضافة سطر</button></div><x-auth-validation-errors class="alert" :errors="$errors" /><div id="records">@foreach($entry->records as $index => $record)<div class="record-row rounded-lg p-4 mb-4" style="background:#f8fbf8;border:1px solid #e3ebe5"><div class="grid grid-cols-1 md:grid-cols-6 gap-3 items-end"><div><label>النوع</label><select name="records[{{ $index }}][type]"><option value="-1" @selected($record->type < 0)>مصروف</option><option value="1" @selected($record->type > 0)>إيراد</option></select></div><div><label>الحساب</label><select name="records[{{ $index }}][account_id]" required>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected($record->account_id == $account->id)>{{ $account->name }}</option>@endforeach</select></div><div><label>التصنيف</label><select name="records[{{ $index }}][category_id]"><option value="">بدون تصنيف</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected($record->category_id == $category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label>المبلغ</label><input type="number" name="records[{{ $index }}][value]" value="{{ $record->value }}" min="0.01" step="0.01" required></div><div><label>الوصف</label><input name="records[{{ $index }}][comment]" value="{{ $record->comment }}" maxlength="255"></div><button type="button" class="remove-record text-red-600">حذف</button></div></div>@endforeach</div><div class="flex justify-end gap-3 mt-6"><a class="btn-light px-5 py-2" href="{{ route('acp.entry.index') }}">إلغاء</a><button class="btn-ms" type="submit">حفظ التعديلات</button></div></div>
    </form></div></div>
    <template id="record-template"><div class="record-row rounded-lg p-4 mb-4" style="background:#f8fbf8;border:1px solid #e3ebe5"><div class="grid grid-cols-1 md:grid-cols-6 gap-3 items-end"><div><label>النوع</label><select name="records[__INDEX__][type]"><option value="-1">مصروف</option><option value="1">إيراد</option></select></div><div><label>الحساب</label><select name="records[__INDEX__][account_id]" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></div><div><label>التصنيف</label><select name="records[__INDEX__][category_id]"><option value="">بدون تصنيف</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div><label>المبلغ</label><input type="number" name="records[__INDEX__][value]" min="0.01" step="0.01" required></div><div><label>الوصف</label><input name="records[__INDEX__][comment]" maxlength="255"></div><button type="button" class="remove-record text-red-600">حذف</button></div></div></template>
    <script>(()=>{const box=document.getElementById('records'),tpl=document.getElementById('record-template').innerHTML,add=document.getElementById('add-record');let i={{ $entry->records->count() }};const bind=r=>r.querySelector('.remove-record').addEventListener('click',()=>r.remove());box.querySelectorAll('.record-row').forEach(bind);add.addEventListener('click',()=>{box.insertAdjacentHTML('beforeend',tpl.replaceAll('__INDEX__',i++));bind(box.lastElementChild)})})();</script>
</x-app-layout>
